name: Oracle Cloud Running

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-claimer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install OCI
        run: pip install oci

      - name: Run Script
        env:
          OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
          OCI_KEY: ${{ secrets.OCI_KEY }}
        run: python claimer.py
